version: "3.8"
services:
  db:
    build: ./LoginBackend/db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blogs
    restart: always
  backend:
    build: ./LoginBackend/server
    environment:
      MYSQL_DATABASE: blogs
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "9000:4000"
    depends_on:
      - db
    restart: on-failure
  frontend:
    build: ./cook
    ports:
      - 3000:3000
